class ApiConstants:
    
    PROCESS_REQUEST_NODE_ATTRIBUTE_TYPE = 'type'
    PROCESS_REQUEST_NODE_ATTRIBUTE_STORAGE = 'storage'
    PROCESS_REQUEST_NODE_ATTRIBUTE_PATH = 'path'
    PROCESS_REQUEST_NODE_ATTRIBUTE_FILENAME = 'filename'
    PROCESS_REQUEST_NODE_ATTRIBUTE_OUTPATH = 'outPath'
    PROCESS_REQUEST_NODE_ATTRIBUTE_PAGE_IMAGE_FILENAME = 'pageImageFilename'
    PROCESS_REQUEST_NODE_ATTRIBUTE_OCR_JSON_FILENAME = 'ocr_json_filename'
    PROCESS_REQUEST_NODE_ATTRIBUTE_OCR_TABLE_JSON_FILENAME = 'ocrTableJsonFilename'
    PROCESS_REQUEST_NODE_ATTRIBUTE_OCR_CUSTOM_JSON_FILENAME = 'ocrCustomJsonFilename'
    PROCESS_REQUEST_NODE_ATTRIBUTE_FORMULAR_TYPE = 'formularType'
    
    PROCESS_REQUEST_NODE_OUTPUT_MESSAGEID = 'messageid'
    PROCESS_REQUEST_NODE_OUTPUT_ERRORS = 'errors'
    PROCESS_REQUEST_NODE_OUTPUT_MESSAGES = 'messages'
    