
class OcrConstants:
    """ Azure cognitive services constants
    """
    STORAGE_TYPE_AZURE = ''
    STORAGE_AZURE_BASE = ''    
    SAS_URL = ''
    
    AZURE_CONNECTION_STRING = ''
    AZURE_SHARE_NAME = ''
    
    COMPUTER_VISION_SUBSCRIPTION_KEY = ''
    COMPUTER_VISION_ENDPOINT = ''
    COMPUTER_VISION_FORM_SUBSCRIPTION_KEY = ''
    COMPUTER_VISION_FORM_ENDPOINT = ''
    
    FORMULAR_CONFIG_AZURE_BASE = ''
    FORMULAR_CONFIG_PATH = ''
    
    
class EnvConstants:
    ENV_STORAGE_AZURE = 'STORAGE_TYPE_AZURE',
    ENV_STORAGE_BASE = 'STORAGE_AZURE_BASE',
    ENV_SASURL = 'SAS_URL',
    ENV_CONNECTION_STRING = 'AZURE_CONNECTION_STRING',
    ENV_SHARE_NAME = 'AZURE_SHARE_NAME',
    ENV_CV_SUBSCRIPTION_KEY = 'COMPUTER_VISION_SUBSCRIPTION_KEY',
    ENV_CV_ENDPOINT = 'COMPUTER_VISION_ENDPOINT',
    ENV_CV_FORM_SUBSCRIPTION_KEY = 'COMPUTER_VISION_FORM_SUBSCRIPTION_KEY',
    ENV_CV_FORM_ENDPOINT = 'COMPUTER_VISION_FORM_ENDPOINT',
    ENV_FRM_CONFIG_AZURE_BASE = 'FORMULAR_CONFIG_AZURE_BASE',
    ENV_FRM_CONFIG_PATH = 'FORMULAR_CONFIG_PATH'
    